"use client";
import { useState } from "react";
import useSWR from "swr";
import { fetcher } from "@/lib/api";
import { HrHeader, LoadState, MetricGrid } from "@/components/hr/HrUi";
type Row = { employee_id: number; employee_no: string | null; full_name: string; arrival_at: string | null; departure_at: string | null; worked_minutes: number; scheduled_minutes: number; variance_minutes: number; status: string };
type Attendance = { day: string; summary: { employees: number; present: number; absent: number; overtime_minutes: number }; rows: Row[] };
function duration(minutes: number) { const sign = minutes < 0 ? "−" : ""; const value = Math.abs(minutes); return `${sign}${Math.floor(value / 60)}h ${value % 60}m`; }
export default function HrAttendancePage() { const [day, setDay] = useState(new Date().toISOString().slice(0, 10)); const { data, error, isLoading, mutate } = useSWR<Attendance>(`/api/hr/attendance?day=${day}`, fetcher);
  return <div><HrHeader title="Attendance & Time Tracking" subtitle="Scheduled versus actual hours from fingerprint, face, RFID and turnstile events." actions={<button className="btn" onClick={() => void mutate()}>Refresh</button>} /><div className="card mb-4 max-w-xs p-4"><label><span className="label">Working date</span><input className="input" type="date" value={day} onChange={(e) => setDay(e.target.value)} /></label></div><MetricGrid items={[{ label: "Employees", value: data?.summary.employees ?? "—" }, { label: "Present", value: data?.summary.present ?? "—" }, { label: "Absent", value: data?.summary.absent ?? "—" }, { label: "Overtime", value: data ? duration(data.summary.overtime_minutes) : "—" }]} /><LoadState loading={isLoading} error={error} empty={!isLoading && !data?.rows.length}><div className="card overflow-x-auto"><table className="table min-w-[850px]"><thead><tr><th>Employee</th><th>Employee ID</th><th>Arrival</th><th>Departure</th><th className="text-right">Scheduled</th><th className="text-right">Actual</th><th className="text-right">Variance</th><th>Status</th></tr></thead><tbody>{data?.rows.map((row) => <tr key={row.employee_id}><td className="font-medium">{row.full_name}</td><td className="font-mono">{row.employee_no || `EMP-${row.employee_id}`}</td><td>{row.arrival_at ? new Date(row.arrival_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</td><td>{row.departure_at ? new Date(row.departure_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</td><td className="text-right tabular-nums">{duration(row.scheduled_minutes)}</td><td className="text-right tabular-nums">{duration(row.worked_minutes)}</td><td className={`text-right font-semibold tabular-nums ${row.variance_minutes < 0 ? "text-red-700" : "text-emerald-700"}`}>{duration(row.variance_minutes)}</td><td><span className={`badge ${row.status === "present" ? "badge-green" : "badge-red"}`}>{row.status}</span></td></tr>)}</tbody></table></div></LoadState></div>;
}
