"use client";
import { useEffect, useState } from "react";
import useSWR from "swr";
import { api, fetcher } from "@/lib/api";
import { HrHeader, LoadState } from "@/components/hr/HrUi";
type Settings = { company_name: string; default_workday_hours: number; default_monthly_hours: number; probation_days: number; contract_warning_days: number; weekend_days: number[] };
export default function HrSettingsPage() { const { data, error, isLoading, mutate } = useSWR<Settings>("/api/hr/settings", fetcher); const [form, setForm] = useState<Settings | null>(null); const [message, setMessage] = useState(""); useEffect(() => { if (data) setForm(data); }, [data]); async function save(e: React.FormEvent) { e.preventDefault(); if (!form) return; setMessage(""); try { await api.put("/api/hr/settings", form); await mutate(); setMessage("HR settings saved."); } catch (err: unknown) { setMessage(String((err as Error)?.message || err)); } }
  return <div><HrHeader title="HR Settings" subtitle="Factory-specific HR defaults only. Global ERP and other department settings are not changed." /><LoadState loading={isLoading} error={error}>{form && <form onSubmit={save} className="card max-w-3xl p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Company name</span><input className="input" value={form.company_name} onChange={(e) => setForm({ ...form, company_name: e.target.value })} /></label><label><span className="label">Default workday hours</span><input className="input" type="number" min="0.25" max="24" step="0.25" value={form.default_workday_hours} onChange={(e) => setForm({ ...form, default_workday_hours: Number(e.target.value) })} /></label><label><span className="label">Default monthly scheduled hours</span><input className="input" type="number" min="0" max="744" step="0.5" value={form.default_monthly_hours} onChange={(e) => setForm({ ...form, default_monthly_hours: Number(e.target.value) })} /></label><label><span className="label">Default probation period (days)</span><input className="input" type="number" min="0" value={form.probation_days} onChange={(e) => setForm({ ...form, probation_days: Number(e.target.value) })} /></label><label><span className="label">Contract expiry warning (days)</span><input className="input" type="number" min="0" value={form.contract_warning_days} onChange={(e) => setForm({ ...form, contract_warning_days: Number(e.target.value) })} /></label></div><div className="mt-5 rounded-lg border border-[#dedbd0] bg-[#fbfaf6] p-3 text-sm text-[#6d6757]">Attendance device configuration remains in the existing attendance integration. These HR settings do not modify terminals, turnstiles, payroll formulas, or other department workflows.</div>{message && <div className={`mt-4 text-sm ${message.includes("saved") ? "text-emerald-700" : "text-red-700"}`}>{message}</div>}<div className="mt-5 flex justify-end"><button className="btn btn-primary">Save HR settings</button></div></form>}</LoadState></div>;
}
