"use client";

import { useMemo, useState } from "react";
import useSWR from "swr";
import { api, fetcher } from "@/lib/api";
import Modal from "@/components/Modal";
import { HrHeader, LoadState, MetricGrid } from "@/components/hr/HrUi";

type Unit = { id: number; parent_id: number | null; department_id: number | null; manager_employee_id: number | null; unit_type: string; name: string; code: string | null; sort_order: number };
type Employee = { id: number; full_name: string; manager_employee_id: number | null; hr_position_id: number | null; position: string | null; status: string };
type Response = { units: Unit[]; employees: Employee[] };

export default function OrganizationPage() {
  const { data, error, isLoading, mutate } = useSWR<Response>("/api/hr/organization", fetcher); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [form, setForm] = useState({ parent_id: "", manager_employee_id: "", unit_type: "section", name: "", code: "" });
  const roots = useMemo(() => (data?.units || []).filter((row) => !row.parent_id), [data]);
  function renderUnit(unit: Unit, depth = 0): React.ReactNode { const children = data?.units.filter((row) => row.parent_id === unit.id) || []; const manager = data?.employees.find((row) => row.id === unit.manager_employee_id); return <div key={unit.id} style={{ marginLeft: depth * 24 }} className="mt-3"><div className="rounded-lg border border-[#dedbd0] bg-white p-3"><div className="text-[10px] font-bold uppercase tracking-wide text-[#8a8472]">{unit.unit_type}</div><div className="font-semibold">{unit.name}</div><div className="mt-1 text-xs text-[#6d6757]">Manager: {manager?.full_name || "Not assigned"}</div></div>{children.map((child) => renderUnit(child, depth + 1))}</div>; }
  async function create(event: React.FormEvent) { event.preventDefault(); setMessage(""); try { await api.post("/api/hr/organization", { parent_id: form.parent_id ? Number(form.parent_id) : null, department_id: null, manager_employee_id: form.manager_employee_id ? Number(form.manager_employee_id) : null, unit_type: form.unit_type, name: form.name, code: form.code || null, sort_order: 0 }); await mutate(); setOpen(false); setForm({ parent_id: "", manager_employee_id: "", unit_type: "section", name: "", code: "" }); } catch (e: unknown) { setMessage(String((e as Error)?.message || e)); } }
  const vacantEmployees = data?.employees.filter((row) => row.status === "active" && !row.hr_position_id).length || 0;
  return <div><HrHeader title="Organization Structure" subtitle="Company → Factory → Department → Section → Team → Position → Employee" actions={<button className="btn btn-primary" onClick={() => setOpen(true)}>Add organization unit</button>} /><MetricGrid items={[{ label: "Organization units", value: data?.units.length ?? "—" }, { label: "Active employees", value: data?.employees.filter((r) => r.status === "active").length ?? "—" }, { label: "Without staffing position", value: vacantEmployees }, { label: "Managers assigned", value: data?.units.filter((r) => r.manager_employee_id).length ?? "—" }]} /><LoadState loading={isLoading} error={error} empty={!isLoading && !roots.length}><div className="card p-5"><div className="overflow-x-auto pb-3">{roots.map((unit) => renderUnit(unit))}</div></div></LoadState>
    <Modal open={open} onClose={() => setOpen(false)} title="Add organization unit"><form className="space-y-3" onSubmit={create}><label><span className="label">Type</span><select className="input" value={form.unit_type} onChange={(e) => setForm({ ...form, unit_type: e.target.value })}>{["company", "factory", "department", "section", "team"].map((v) => <option key={v}>{v}</option>)}</select></label><label><span className="label">Name</span><input className="input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span className="label">Parent unit</span><select className="input" value={form.parent_id} onChange={(e) => setForm({ ...form, parent_id: e.target.value })}><option value="">Root level</option>{data?.units.map((row) => <option value={row.id} key={row.id}>{row.unit_type}: {row.name}</option>)}</select></label><label><span className="label">Manager</span><select className="input" value={form.manager_employee_id} onChange={(e) => setForm({ ...form, manager_employee_id: e.target.value })}><option value="">Not assigned</option>{data?.employees.map((row) => <option value={row.id} key={row.id}>{row.full_name}</option>)}</select></label><label><span className="label">Code</span><input className="input" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></label>{message && <div className="text-sm text-red-700">{message}</div>}<div className="flex justify-end gap-2"><button className="btn" type="button" onClick={() => setOpen(false)}>Cancel</button><button className="btn btn-primary">Add unit</button></div></form></Modal>
  </div>;
}
