"use client";
import { useState } from "react";
import useSWRInfinite from "swr/infinite";
import { api, fetcher } from "@/lib/api";
import { useHrCalendarEmployees } from "@/lib/useHrCalendarEmployees";
import Modal from "@/components/Modal";
import { HrHeader, LoadState, MetricGrid } from "@/components/hr/HrUi";
type Event = { id: number; employee_id: number | null; event_type: string; title: string; starts_at: string; ends_at: string | null; notes: string | null; status: string };
type CalendarPage = { rows: Event[]; total: number; page: number; page_size: number; has_more: boolean; metrics: { upcoming: number; contracts_expiring: number; probation_ending: number; training: number } };
const TYPES = ["birthday", "contract_expiry", "probation_end", "leave", "training", "interview", "medical_check", "certification", "performance_review", "other"];
export default function HrCalendarPage() { const { data: pages, error, isLoading, mutate, setSize } = useSWRInfinite<CalendarPage>((index) => `/api/hr/calendar?page=${index + 1}&page_size=100`, fetcher); const [open, setOpen] = useState(false); const { data: employees } = useHrCalendarEmployees(open); const [message, setMessage] = useState(""); const [form, setForm] = useState({ employee_id: "", event_type: "leave", title: "", starts_at: "", ends_at: "", notes: "", status: "scheduled" });
  const data = pages?.flatMap((page) => page.rows) || [];
  const metrics = pages?.[0]?.metrics;
  const lastPage = pages?.[pages.length - 1];
  const loadMore = () => { if (lastPage?.has_more) void setSize((pages?.length || 0) + 1); };
  async function create(e: React.FormEvent) { e.preventDefault(); setMessage(""); try { await api.post("/api/hr/calendar", { ...form, employee_id: form.employee_id ? Number(form.employee_id) : null, starts_at: new Date(form.starts_at).toISOString(), ends_at: form.ends_at ? new Date(form.ends_at).toISOString() : null }); await mutate(); setOpen(false); } catch (err: unknown) { setMessage(String((err as Error)?.message || err)); } }
  return <div><HrHeader title="HR Calendar" subtitle="One calendar for employee milestones, leave, training, checks and reviews." actions={<button className="btn btn-primary" onClick={() => setOpen(true)}>Add event</button>} /><MetricGrid items={[{ label: "Upcoming", value: metrics?.upcoming ?? "—" }, { label: "Contracts expiring", value: metrics?.contracts_expiring ?? "—" }, { label: "Probation ending", value: metrics?.probation_ending ?? "—" }, { label: "Training", value: metrics?.training ?? "—" }]} /><LoadState loading={isLoading} error={error} empty={!isLoading && !data.length}><div className="card divide-y divide-[#ecebe3]">{data.map((row) => <div className="grid gap-3 p-4 sm:grid-cols-[130px_1fr_180px_100px] sm:items-center" key={row.id}><div className="text-sm font-semibold tabular-nums">{new Date(row.starts_at).toLocaleDateString()}<div className="text-xs font-normal text-[#8a8472]">{new Date(row.starts_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div></div><div><div className="font-medium">{row.title}</div><div className="text-xs capitalize text-[#8a8472]">{row.event_type.replaceAll("_", " ")}</div></div><div className="text-sm">{employees?.find((e) => e.id === row.employee_id)?.full_name || "Company event"}</div><span className="badge">{row.status}</span></div>)}{lastPage?.has_more && <button className="btn m-3" onClick={loadMore}>Load more</button>}</div></LoadState><Modal open={open} onClose={() => setOpen(false)} title="Add HR event"><form className="space-y-3" onSubmit={create}><select className="input" value={form.event_type} onChange={(e) => setForm({ ...form, event_type: e.target.value })}>{TYPES.map((v) => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select><input className="input" required placeholder="Event title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><select className="input" value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })}><option value="">Company event</option>{employees?.map((r) => <option value={r.id} key={r.id}>{r.full_name}</option>)}</select><label><span className="label">Starts</span><input className="input" required type="datetime-local" value={form.starts_at} onChange={(e) => setForm({ ...form, starts_at: e.target.value })} /></label><label><span className="label">Ends (optional)</span><input className="input" type="datetime-local" value={form.ends_at} onChange={(e) => setForm({ ...form, ends_at: e.target.value })} /></label><textarea className="input" placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} />{message && <div className="text-sm text-red-700">{message}</div>}<button className="btn btn-primary w-full">Add event</button></form></Modal></div>;
}
