"use client";
import { useState } from "react";
import useSWR from "swr";
import { api, fetcher } from "@/lib/api";
import Modal from "@/components/Modal";
import { HrHeader, LoadState, MetricGrid } from "@/components/hr/HrUi";
type Employee = { id: number; full_name: string };
type Document = { id: number; employee_id: number; employee_name: string; category: string; title: string; original_name: string; size_bytes: number; expires_on: string | null; created_at: string; download_url: string };
const CATEGORIES = ["employment_contract", "passport_id", "diploma", "certificate", "employment_order", "salary_amendment", "leave", "disciplinary", "training", "resignation", "other"];
export default function DocumentsPage() { const { data, error, isLoading, mutate } = useSWR<Document[]>("/api/hr/documents", fetcher); const { data: employees } = useSWR<Employee[]>("/api/employees", fetcher); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [form, setForm] = useState({ employee_id: "", category: "employment_contract", title: "", expires_on: "", file: null as File | null });
  async function upload(e: React.FormEvent) { e.preventDefault(); if (!form.file) return; setBusy(true); setMessage(""); const body = new FormData(); body.append("employee_id", form.employee_id); body.append("category", form.category); body.append("title", form.title); if (form.expires_on) body.append("expires_on", form.expires_on); body.append("file", form.file); try { await api.postForm("/api/hr/documents", body); await mutate(); setOpen(false); } catch (err: unknown) { setMessage(String((err as Error)?.message || err)); } finally { setBusy(false); } }
  const expiring = data?.filter((r) => r.expires_on && new Date(r.expires_on).getTime() < Date.now() + 30 * 86400000).length || 0;
  return <div><HrHeader title="Employee Documents" subtitle="Secure, factory-scoped digital personnel archive." actions={<button className="btn btn-primary" onClick={() => setOpen(true)}>Upload document</button>} /><MetricGrid items={[{ label: "Documents", value: data?.length ?? "—" }, { label: "Employee folders", value: new Set(data?.map((r) => r.employee_id)).size }, { label: "Expiring in 30 days", value: expiring }, { label: "Archive size", value: `${((data?.reduce((n, r) => n + r.size_bytes, 0) || 0) / 1048576).toFixed(1)} MB` }]} /><LoadState loading={isLoading} error={error} empty={!isLoading && !data?.length}><div className="card overflow-x-auto"><table className="table"><thead><tr><th>Employee</th><th>Category</th><th>Document</th><th>Expiry</th><th>Uploaded</th><th /></tr></thead><tbody>{data?.map((row) => <tr key={row.id}><td>{row.employee_name}</td><td className="capitalize">{row.category.replaceAll("_", " ")}</td><td><div className="font-medium">{row.title}</div><div className="text-xs text-[#8a8472]">{row.original_name}</div></td><td>{row.expires_on ? new Date(row.expires_on).toLocaleDateString() : "—"}</td><td>{new Date(row.created_at).toLocaleDateString()}</td><td><a className="text-brand-600 hover:underline" href={row.download_url}>Download</a></td></tr>)}</tbody></table></div></LoadState><Modal open={open} onClose={() => setOpen(false)} title="Upload employee document"><form className="space-y-3" onSubmit={upload}><select className="input" required value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })}><option value="">Select employee</option>{employees?.map((r) => <option value={r.id} key={r.id}>{r.full_name}</option>)}</select><select className="input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{CATEGORIES.map((v) => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}</select><input className="input" required placeholder="Document title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><label><span className="label">Expiration date (optional)</span><input className="input" type="date" value={form.expires_on} onChange={(e) => setForm({ ...form, expires_on: e.target.value })} /></label><input className="input" required type="file" onChange={(e) => setForm({ ...form, file: e.target.files?.[0] || null })} />{message && <div className="text-sm text-red-700">{message}</div>}<button className="btn btn-primary w-full" disabled={busy}>{busy ? "Uploading…" : "Upload securely"}</button></form></Modal></div>;
}
