"use client";

import { useState } from "react";
import useSWR from "swr";
import { api, fetcher } from "@/lib/api";
import Modal from "@/components/Modal";
import { HrHeader, LoadState, MetricGrid } from "@/components/hr/HrUi";

type Dept = { id: number; name: string };
type Position = { id: number; department_id: number | null; name: string; job_description: string | null; required_skills: string[]; qualification_level: string | null; grade_level: string | null; salary_min: number | null; salary_max: number | null; approved_count: number; occupied_count: number; vacant_count: number; is_active: boolean };
const EMPTY = { department_id: "", name: "", job_description: "", required_skills: "", qualification_level: "", grade_level: "", salary_min: "", salary_max: "", approved_count: "0", is_active: true };

export default function PositionsPage() {
  const { data, error, isLoading, mutate } = useSWR<Position[]>("/api/hr/positions", fetcher);
  const { data: departments } = useSWR<Dept[]>("/api/departments", fetcher);
  const [editing, setEditing] = useState<Position | "new" | null>(null); const [form, setForm] = useState(EMPTY); const [message, setMessage] = useState("");
  const totals = (data || []).reduce((sum, row) => ({ plan: sum.plan + row.approved_count, actual: sum.actual + row.occupied_count, vacant: sum.vacant + row.vacant_count }), { plan: 0, actual: 0, vacant: 0 });
  function open(row?: Position) { setEditing(row || "new"); setMessage(""); setForm(row ? { department_id: row.department_id ? String(row.department_id) : "", name: row.name, job_description: row.job_description || "", required_skills: row.required_skills.join(", "), qualification_level: row.qualification_level || "", grade_level: row.grade_level || "", salary_min: row.salary_min == null ? "" : String(row.salary_min), salary_max: row.salary_max == null ? "" : String(row.salary_max), approved_count: String(row.approved_count), is_active: row.is_active } : EMPTY); }
  async function save(event: React.FormEvent) { event.preventDefault(); setMessage(""); const payload = { department_id: form.department_id ? Number(form.department_id) : null, org_unit_id: null, name: form.name, job_description: form.job_description || null, required_skills: form.required_skills.split(",").map((v) => v.trim()).filter(Boolean), qualification_level: form.qualification_level || null, grade_level: form.grade_level || null, salary_min: form.salary_min === "" ? null : Number(form.salary_min), salary_max: form.salary_max === "" ? null : Number(form.salary_max), approved_count: Number(form.approved_count), is_active: form.is_active }; try { if (editing === "new") await api.post("/api/hr/positions", payload); else await api.patch(`/api/hr/positions/${editing?.id}`, payload); await mutate(); setEditing(null); } catch (e: unknown) { setMessage(String((e as Error)?.message || e)); } }
  return <div><HrHeader title="Positions & Staffing Plan" subtitle="Approved staffing table with live occupancy and vacancy counts." actions={<button className="btn btn-primary" onClick={() => open()}>Add position</button>} />
    <MetricGrid items={[{ label: "Approved positions", value: totals.plan }, { label: "Currently occupied", value: totals.actual }, { label: "Vacant", value: totals.vacant }, { label: "Fill rate", value: totals.plan ? `${Math.round(totals.actual / totals.plan * 100)}%` : "0%" }]} />
    <LoadState loading={isLoading} error={error} empty={!isLoading && !data?.length}><div className="card overflow-x-auto"><table className="table min-w-[900px]"><thead><tr><th>Position</th><th>Department</th><th>Qualification</th><th>Salary range</th><th className="text-right">Plan</th><th className="text-right">Actual</th><th className="text-right">Vacancy</th><th /></tr></thead><tbody>{data?.map((row) => <tr key={row.id}><td><div className="font-medium">{row.name}</div><div className="text-xs text-[#8a8472]">{row.required_skills.join(", ") || "No skills specified"}</div></td><td>{departments?.find((d) => d.id === row.department_id)?.name || "—"}</td><td>{row.qualification_level || row.grade_level || "—"}</td><td>{row.salary_min == null && row.salary_max == null ? "—" : `${row.salary_min ?? 0} – ${row.salary_max ?? "∞"}`}</td><td className="text-right tabular-nums">{row.approved_count}</td><td className="text-right tabular-nums">{row.occupied_count}</td><td className={`text-right font-semibold tabular-nums ${row.vacant_count ? "text-amber-700" : "text-emerald-700"}`}>{row.vacant_count}</td><td><button className="text-brand-600 hover:underline" onClick={() => open(row)}>Edit</button></td></tr>)}</tbody></table></div></LoadState>
    <Modal open={editing !== null} onClose={() => setEditing(null)} title={editing === "new" ? "New staffing position" : "Edit staffing position"} wide><form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><label><span className="label">Position name</span><input className="input" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span className="label">Department</span><select className="input" value={form.department_id} onChange={(e) => setForm({ ...form, department_id: e.target.value })}><option value="">Unassigned</option>{departments?.map((d) => <option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label><span className="label">Qualification level</span><input className="input" value={form.qualification_level} onChange={(e) => setForm({ ...form, qualification_level: e.target.value })} /></label><label><span className="label">Grade / level</span><input className="input" value={form.grade_level} onChange={(e) => setForm({ ...form, grade_level: e.target.value })} /></label><label><span className="label">Salary minimum</span><input className="input" type="number" min="0" value={form.salary_min} onChange={(e) => setForm({ ...form, salary_min: e.target.value })} /></label><label><span className="label">Salary maximum</span><input className="input" type="number" min="0" value={form.salary_max} onChange={(e) => setForm({ ...form, salary_max: e.target.value })} /></label><label><span className="label">Approved positions</span><input className="input" type="number" min="0" required value={form.approved_count} onChange={(e) => setForm({ ...form, approved_count: e.target.value })} /></label><label><span className="label">Required skills (comma separated)</span><input className="input" value={form.required_skills} onChange={(e) => setForm({ ...form, required_skills: e.target.value })} /></label><label className="sm:col-span-2"><span className="label">Job description</span><textarea className="input min-h-24" value={form.job_description} onChange={(e) => setForm({ ...form, job_description: e.target.value })} /></label>{message && <div className="text-sm text-red-700 sm:col-span-2">{message}</div>}<div className="flex justify-end gap-2 sm:col-span-2"><button type="button" className="btn" onClick={() => setEditing(null)}>Cancel</button><button className="btn btn-primary">Save</button></div></form></Modal>
  </div>;
}
