"""Canonical bundle numbers, retaining permanent references for old printed labels."""
from collections import Counter
import re

from alembic import op
import sqlalchemy as sa

revision = "0120_canonical_bundle_references"
down_revision = "0119_canonical_order_references"
branch_labels = None
depends_on = None


def plan_bundles(records, aliases=()):
    """Preserve canonical identities and unique suffixes without truncating or reuse."""
    records = sorted(records, key=lambda row: int(row["id"]))
    if len(records) > 9999:
        raise RuntimeError("BND: more than 9999 bundles cannot use four-digit references")
    reserved = {}
    for alias in aliases:
        for field in ("reference", "canonical_reference"):
            match = re.fullmatch(r"BND-([0-9]{4})", alias[field])
            if match and 1 <= int(match[1]) <= 9999:
                number = int(match[1])
                if number in reserved and reserved[number] != alias["entity_id"]:
                    raise RuntimeError("BND: conflicting historical identity reservation")
                reserved[number] = alias["entity_id"]
    used = set(reserved)
    assigned, candidates = {}, {}
    for row in records:
        reference = str(row["reference"] or "")
        exact = re.fullmatch(r"BND-([0-9]{4})", reference)
        if exact and 1 <= int(exact[1]) <= 9999:
            number = int(exact[1])
            if number in reserved and reserved[number] != row["id"]:
                raise RuntimeError("BND: existing canonical identity conflicts with historical alias")
            if number in assigned.values():
                raise RuntimeError("BND: duplicate canonical identity")
            assigned[row["id"]] = number
            used.add(number)
            continue
        legacy = re.fullmatch(r"BND-(?:[0-9]{4}-)?([0-9]+)", reference, re.I)
        if legacy and 1 <= int(legacy[1]) <= 9999:
            candidates[row["id"]] = int(legacy[1])
    counts = Counter(candidates.values())
    for entity_id, number in candidates.items():
        if counts[number] == 1 and number not in used:
            assigned[entity_id] = number
            used.add(number)
    free = (number for number in range(1, 10000) if number not in used)
    for row in records:
        if row["id"] not in assigned:
            number = next(free, None)
            if number is None:
                raise RuntimeError("BND: four-digit namespace is exhausted, including historical reservations")
            assigned[row["id"]] = number
    plans = [dict(namespace="BND", entity_id=row["id"], reference=str(row["reference"] or ""),
                  canonical_reference=f"BND-{assigned[row['id']]:04d}") for row in records]
    existing = {alias["reference"]: alias for alias in aliases}
    for row in plans:
        for reference in (row["reference"], row["canonical_reference"]):
            old = existing.get(reference)
            if old and (old["entity_id"] != row["entity_id"] or old["canonical_reference"] != row["canonical_reference"]):
                raise RuntimeError("BND: historical alias would change identity")
    return plans


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("SET LOCAL lock_timeout = '10s'")
        op.execute("SET LOCAL statement_timeout = '120s'")
        op.execute("LOCK TABLE bundles, business_order_aliases IN SHARE ROW EXCLUSIVE MODE")
    metadata = sa.MetaData()
    bundles = sa.Table("bundles", metadata, autoload_with=bind)
    aliases = sa.Table("business_order_aliases", metadata, autoload_with=bind)
    rows = [dict(row) for row in bind.execute(sa.select(bundles.c.id, bundles.c.bundle_no.label("reference"))).mappings()]
    old_aliases = [dict(row) for row in bind.execute(sa.select(aliases).where(aliases.c.namespace == "BND")).mappings()]
    plans = plan_bundles(rows, old_aliases)
    # No dependent bundle-number columns exist: scan/receipt links use bundle IDs.
    # Live QR payloads are generated by bundle-image; barcode and audit snapshots stay intact.
    existing = {row["reference"] for row in old_aliases}
    inserts = []
    for row in plans:
        for reference in (row["reference"], row["canonical_reference"]):
            if reference not in existing:
                inserts.append(dict(row, reference=reference))
                existing.add(reference)
    changed = [row for row in plans if row["reference"] != row["canonical_reference"]]
    occupied = {row["reference"] for row in rows} | {row["canonical_reference"] for row in plans}
    staged = {}
    for row in changed:
        temporary = f"__bundle_0120_{row['entity_id']}"
        while temporary in occupied:
            temporary += "_"
        occupied.add(temporary)
        staged[row["entity_id"]] = temporary
    if inserts:
        bind.execute(aliases.insert(), inserts)
    for entity_id, temporary in staged.items():
        bind.execute(bundles.update().where(bundles.c.id == entity_id).values(bundle_no=temporary))
    for row in changed:
        bind.execute(bundles.update().where(bundles.c.id == row["entity_id"]).values(bundle_no=row["canonical_reference"]))
    bind.execute(bundles.update().values(qr_code_url=sa.literal("/api/barcode/bundle-image/") + sa.cast(bundles.c.id, sa.String)))


def downgrade():
    raise RuntimeError("Canonical bundle references require a reviewed rollback mapping; restore the pre-migration backup")
