export const stocktakeText = {
  en: {
    recovered: "Unsaved scans recovered for this count. Retry to save them; saved scans will not be counted twice.",
    storageError: "Browser storage is unavailable. Keep this page open and copy any unsaved codes before leaving.",
    scanHistory: "Scan history — newest first", historySaved: "Saved scans remain in this count when you reload or reopen it.",
    scannedPackages: "Scanned packs", scannedPieces: "Scanned pieces", scannedAt: "Scanned at",
    unresolvedModel: "Model not identified", unresolvedPieces: "Unknown",
    estimatedScan: "Uses count-start quantity", estimatedTotal: "Packs using count-start quantities", unquantifiedTotal: "Packs with unknown quantity",
    scannerReady: "Scanner ready. Keep scanning with Enter or Tab; scans save automatically.",
    title: "Inventory count", intro: "Scan every pack in the finished-goods warehouse. Counts are saved automatically and do not adjust stock.",
    start: "Start count", name: "Count name", history: "Saved counts", open: "In progress", complete: "Completed", back: "All counts",
    empty: "No inventory counts yet.", loading: "Loading…", scan: "Scan package QR or barcode", add: "Record scan", retry: "Retry unsaved scans",
    pending: "Scans waiting to save", discard: "Discard unsaved scans", discardConfirm: "Discard these unsaved scans? Copy the codes first if you need to record them in another count.", saved: "Saved", duplicate: "Already counted — not counted again", expected: "Expected packs",
    found: "Found", missing: "Not scanned yet", missingFinal: "Missing / not found", unknown: "Not in ERP", unexpected: "Not in starting stock",
    ambiguous: "Ambiguous barcode", changed: "Changed during count", all: "All results", scanned: "Recorded scans", search: "Search package, barcode or model",
    result: "Result", package: "Package / scanned code", model: "Model / color", qty: "Pieces", location: "Location", status: "ERP status",
    undo: "Undo scan", finish: "Finish count", download: "Download CSV", previous: "Previous", next: "Next", noRows: "No matching results.",
    finishConfirm: "Finish the whole warehouse count? Unscanned starting packs will be listed as missing. Results will be locked; stock quantities will stay unchanged.",
    undoConfirm: "Remove this scan from the count? The package and stock will stay unchanged.",
    movement: "Stock, package details or location changed after the snapshot. Review these rows before making corrections.",
    unknownHelp: "Unrecognized labels are saved for review. Ambiguous legacy barcodes require the exact package QR; undo the ambiguous scan after checking it.",
    snapshot: "Expected packs are received, reserved and damaged packs at the start, across the finished-goods warehouse. New receipts and departures during counting need review.",
    current: "Current", deleted: "No longer in ERP", denied: "Warehouse package or shipment access is required.", leave: "Some scans have not been saved yet.",
  },
  ru: {
    recovered: "Восстановлены несохранённые сканы этой проверки. Повторите сохранение; сохранённые сканы не будут учтены дважды.",
    storageError: "Хранилище браузера недоступно. Не закрывайте страницу и скопируйте несохранённые коды перед выходом.",
    scanHistory: "История сканов — новые сверху", historySaved: "Сохранённые сканы остаются в проверке после обновления или повторного открытия.",
    scannedPackages: "Сканировано упаковок", scannedPieces: "Сканировано штук", scannedAt: "Время сканирования",
    unresolvedModel: "Модель не определена", unresolvedPieces: "Неизвестно",
    estimatedScan: "Количество на начало проверки", estimatedTotal: "Упаковки с количеством на начало проверки", unquantifiedTotal: "Упаковки с неизвестным количеством",
    scannerReady: "Сканер готов. Сканируйте подряд с Enter или Tab — сканы сохраняются автоматически.",
    title: "Инвентаризация", intro: "Сканируйте каждую упаковку на складе готовой продукции. Результаты сохраняются автоматически и не меняют остатки.",
    start: "Начать инвентаризацию", name: "Название проверки", history: "Сохранённые проверки", open: "В процессе", complete: "Завершена", back: "Все проверки",
    empty: "Проверок пока нет.", loading: "Загрузка…", scan: "Сканируйте QR или штрихкод упаковки", add: "Записать скан", retry: "Повторить несохранённые сканы",
    pending: "Ожидают сохранения", discard: "Удалить несохранённые сканы", discardConfirm: "Удалить несохранённые сканы? Сначала скопируйте коды, если нужно записать их в другую проверку.", saved: "Сохранено", duplicate: "Уже учтено — повтор не засчитан", expected: "Ожидаемые упаковки",
    found: "Найдены", missing: "Ещё не сканированы", missingFinal: "Отсутствуют / не найдены", unknown: "Нет в ERP", unexpected: "Нет в начальных остатках",
    ambiguous: "Неоднозначный штрихкод", changed: "Изменились за время проверки", all: "Все результаты", scanned: "Записанные сканы", search: "Поиск упаковки, штрихкода или модели",
    result: "Результат", package: "Упаковка / код", model: "Модель / цвет", qty: "Штуки", location: "Место", status: "Статус в ERP",
    undo: "Отменить скан", finish: "Завершить проверку", download: "Скачать CSV", previous: "Назад", next: "Далее", noRows: "Нет подходящих результатов.",
    finishConfirm: "Завершить проверку всего склада? Несканированные упаковки из начальных остатков будут отмечены как отсутствующие. Результаты будут закрыты для изменений; остатки не изменятся.",
    undoConfirm: "Удалить этот скан из проверки? Упаковка и остатки не изменятся.",
    movement: "После начала проверки изменились остатки, данные упаковки или место. Проверьте эти строки перед корректировками.",
    unknownHelp: "Неизвестные коды сохраняются для проверки. Для неоднозначного старого штрихкода сканируйте точный QR упаковки; после проверки отмените неоднозначный скан.",
    snapshot: "Начальный список включает принятые, зарезервированные и повреждённые упаковки всего склада готовой продукции. Приходы и отгрузки во время проверки требуют сверки.",
    current: "Сейчас", deleted: "Больше нет в ERP", denied: "Необходим доступ к упаковкам или отгрузкам склада.", leave: "Некоторые сканы ещё не сохранены.",
  },
  uz: {
    recovered: "Bu tekshiruvning saqlanmagan skanlari tiklandi. Saqlashni qayta yuboring; saqlangan skanlar ikki marta hisoblanmaydi.",
    storageError: "Brauzer xotirasi mavjud emas. Sahifani ochiq qoldiring va chiqishdan oldin saqlanmagan kodlarni nusxalang.",
    scanHistory: "Skanlar tarixi — yangilari yuqorida", historySaved: "Saqlangan skanlar sahifani yangilaganda yoki qayta ochganda shu tekshiruvda qoladi.",
    scannedPackages: "Skanerlangan qadoqlar", scannedPieces: "Skanerlangan donalar", scannedAt: "Skanerlangan vaqt",
    unresolvedModel: "Model aniqlanmagan", unresolvedPieces: "Noma’lum",
    estimatedScan: "Tekshiruv boshidagi miqdor", estimatedTotal: "Boshlang‘ich miqdor ishlatilgan qadoqlar", unquantifiedTotal: "Miqdori noma’lum qadoqlar",
    scannerReady: "Skaner tayyor. Enter yoki Tab bilan ketma-ket skanerlang — skanlar avtomatik saqlanadi.",
    title: "Inventarizatsiya", intro: "Tayyor mahsulot omboridagi har bir qadoqni skanerlang. Natijalar avtomatik saqlanadi va qoldiqni o‘zgartirmaydi.",
    start: "Tekshiruvni boshlash", name: "Tekshiruv nomi", history: "Saqlangan tekshiruvlar", open: "Davom etmoqda", complete: "Yakunlangan", back: "Barcha tekshiruvlar",
    empty: "Hali tekshiruvlar yo‘q.", loading: "Yuklanmoqda…", scan: "Qadoq QR yoki shtrix-kodini skanerlang", add: "Skanni yozish", retry: "Saqlanmagan skanlarni qayta yuborish",
    pending: "Saqlashni kutayotgan skanlar", discard: "Saqlanmagan skanlarni o‘chirish", discardConfirm: "Saqlanmagan skanlar o‘chirilsinmi? Boshqa tekshiruvga yozish kerak bo‘lsa, avval kodlarni nusxalang.", saved: "Saqlandi", duplicate: "Avval hisoblangan — qayta hisoblanmadi", expected: "Kutilgan qadoqlar",
    found: "Topildi", missing: "Hali skanerlanmagan", missingFinal: "Yo‘q / topilmadi", unknown: "ERPda yo‘q", unexpected: "Boshlang‘ich qoldiqda yo‘q",
    ambiguous: "Noaniq shtrix-kod", changed: "Tekshiruv davomida o‘zgargan", all: "Barcha natijalar", scanned: "Yozilgan skanlar", search: "Qadoq, shtrix-kod yoki modelni qidirish",
    result: "Natija", package: "Qadoq / skanerlangan kod", model: "Model / rang", qty: "Dona", location: "Joylashuv", status: "ERPdagi holat",
    undo: "Skanni bekor qilish", finish: "Tekshiruvni yakunlash", download: "CSV yuklab olish", previous: "Oldingi", next: "Keyingi", noRows: "Mos natijalar yo‘q.",
    finishConfirm: "Butun ombor tekshiruvini yakunlaysizmi? Boshlang‘ich ro‘yxatdagi skanerlanmagan qadoqlar topilmagan deb belgilanadi. Natijalar yopiladi; ombor qoldig‘i o‘zgarmaydi.",
    undoConfirm: "Bu skanni tekshiruvdan olib tashlaysizmi? Qadoq va ombor qoldig‘i o‘zgarmaydi.",
    movement: "Tekshiruv boshlanganidan keyin qoldiq, qadoq ma’lumoti yoki joylashuvi o‘zgargan. Tuzatishdan oldin shu qatorlarni tekshiring.",
    unknownHelp: "Noma’lum kodlar tekshirish uchun saqlanadi. Noaniq eski shtrix-kod o‘rniga qadoqning aniq QR kodini skanerlang; tekshirgandan keyin noaniq skanni bekor qiling.",
    snapshot: "Boshlang‘ich ro‘yxat butun tayyor mahsulot omboridagi qabul qilingan, band qilingan va shikastlangan qadoqlarni qamrab oladi. Tekshiruv paytidagi kirim va chiqimlarni solishtirish kerak.",
    current: "Hozir", deleted: "Endi ERPda yo‘q", denied: "Ombor qadoqlari yoki jo‘natmalarga kirish huquqi kerak.", leave: "Ba’zi skanlar hali saqlanmadi.",
  },
} as const;
